name: TEST AutoDispatch
on: 
  repository_dispatch:
    push:
    branches:
      - main
  push:
jobs:
  dispatches:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I was ran from another repo"
